[package]
name = "oci-reference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.1"
lazy_static = "0.1"

[dev-dependencies]
rstest = "0.22"

[lints]
workspace = true
